### ISSUE TITLE
'ModuleNotFoundError: No module named 'tools.commons' in docker-fish-speech

### ISSUE THREAD

**Issue by ngc-shj** [janhq/ichigo-demo#16]
Thank you for a great job.
When I run the docker-compose up command, I get an error during the docker-fis-speech startup process saying that tools.commons cannot be found.

I'd like to know if there is a workaround.

```bash
docker-fish-speech-1     | Process SpawnProcess-1:
docker-fish-speech-1     | Traceback (most recent call last):
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
docker-fish-speech-1     |     self.run()
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
docker-fish-speech-1     |     self._target(*self._args, **self._kwargs)
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
docker-fish-speech-1     |     target(sockets=sockets)
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/supervisors/multiprocess.py", line 63, in target
docker-fish-speech-1     |     return self.real_target(sockets)
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
docker-fish-speech-1     |     return asyncio.run(self.serve(sockets=sockets))
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
docker-fish-speech-1     |     return runner.run(main)
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
docker-fish-speech-1     |     return self._loop.run_until_complete(task)
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
docker-fish-speech-1     |     return future.result()
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
docker-fish-speech-1     |     await self._serve(sockets)
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
docker-fish-speech-1     |     config.load()
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
docker-fish-speech-1     |     self.loaded_app = import_from_string(self.app)
docker-fish-speech-1     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 22, in import_from_string
docker-fish-speech-1     |     raise exc from None
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
docker-fish-speech-1     |     module = importlib.import_module(module_str)
docker-fish-speech-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
docker-fish-speech-1     |     return _bootstrap._gcd_import(name[level:], package, level)
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
docker-fish-speech-1     |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
docker-fish-speech-1     |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
docker-fish-speech-1     |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
docker-fish-speech-1     |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
docker-fish-speech-1     |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
docker-fish-speech-1     |   File "/opt/fish-speech/api.py", line 59, in <module>
docker-fish-speech-1     |     from tools.commons import ServeReferenceAudio, ServeTTSRequest
docker-fish-speech-1     | ModuleNotFoundError: No module named 'tools.commons'
docker-fish-speech-1     | Process SpawnProcess-3:
docker-fish-speech-1     | Traceback (most recent call last):
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
docker-fish-speech-1     |     self.run()
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
docker-fish-speech-1     |     self._target(*self._args, **self._kwargs)
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
docker-fish-speech-1     |     target(sockets=sockets)
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/supervisors/multiprocess.py", line 63, in target
docker-fish-speech-1     |     return self.real_target(sockets)
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
docker-fish-speech-1     |     return asyncio.run(self.serve(sockets=sockets))
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
docker-fish-speech-1     |     return runner.run(main)
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
docker-fish-speech-1     |     return self._loop.run_until_complete(task)
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
docker-fish-speech-1     |     return future.result()
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
docker-fish-speech-1     |     await self._serve(sockets)
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
docker-fish-speech-1     |     config.load()
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
docker-fish-speech-1     |     self.loaded_app = import_from_string(self.app)
docker-fish-speech-1     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 22, in import_from_string
docker-fish-speech-1     |     raise exc from None
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
docker-fish-speech-1     |     module = importlib.import_module(module_str)
docker-fish-speech-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
docker-fish-speech-1     |     return _bootstrap._gcd_import(name[level:], package, level)
docker-fish-speech-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-fish-speech-1     |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
docker-fish-speech-1     |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
docker-fish-speech-1     |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
docker-fish-speech-1     |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
docker-fish-speech-1     |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
docker-fish-speech-1     |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
docker-fish-speech-1     |   File "/opt/fish-speech/api.py", line 59, in <module>
docker-fish-speech-1     |     from tools.commons import ServeReferenceAudio, ServeTTSRequest
docker-fish-speech-1     | ModuleNotFoundError: No module named 'tools.commons'```

**Comment by nguyenhoangthuan99** [comment]
Hi @ngc-shj , I just noticed that fishaudio has updated their docker inage for fishspeech 2 days ago, can you change the base image for ‘fish-speech’ to “fishaudio/fish-speech:v1.4.2-dev“ and rebuild the image.

**Comment by ngc-shj** [comment]
@nguyenhoangthuan99 
Thank you for your quick response!
I changed the configuration value of the fish-speech base image and it started up successfully!

![スクリーンショット 2024-11-10 142532](https://github.com/user-attachments/assets/a56fbb36-45a8-420d-af38-f34ba8785d36)
